spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xz?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: yangzhixuan
    driver-class-name: com.mysql.cj.jdbc.Driver